---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
configurations:
- kustomize-config.yaml
resources:
- ../../bases/v1.17.1
- ./sealed-secrets.yaml
secretGenerator:
- name: harbor-credentials
  files:
    - ./sealed-secrets.yaml
  options:
    annotations:
      config.kubernetes.io/local-config: "true"
patches:
- patch: |-
    - op: replace
      path: /spec/storageClassName
      value: microk8s-hostpath
  target:
    kind: PersistentVolumeClaim
- patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 300Gi
  target:
    kind: PersistentVolumeClaim
    name: harbor-registry
- patch: |-
    - op: replace
      path: /spec/resources/requests/storage
      value: 10Gi
  target:
    kind: PersistentVolumeClaim
    name: harbor-jobservice