---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: harbor-credentials
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgACMq3qsSgEYOeliyrjvO5dZf06FsPlN1yi4j1ab6qMKB5KDI72MJxRh8Rf/ZdaWpcGHd8QANKjziuC88JuEKPVEBCq8bUe6sE2N/WVMEECafR7SgphKT3t5oJmxX6/O0R6T8l8wBIN4u+iHBtT+uum8HUM/8XuJrIb7ndowLEOZdapa4wm0sulfqHH5PLDguLK5Hu+dMwvlM42x3IIWHP3TcawV0CcsVROL4HKIm3ky3ngenr9ScJI9+wZUpIZ8B5NORq/wkR2FYM5tCWnbbxs3m2LRDCikTPU4qMsuDkIXU5zl9x0B8TaiGooSp7ozp2xzVBFGZPlGsNxX8VeoHej5CBi6GnkmQJoV6lAl+GYzIp74A+eooRI0+zpR9sx1hNqHp2EjoUWj8jPQrHJqeOZsfKGvjkr3wWuAMpNfZ2ddSwjy/vO6yEB86m/O/ZX8FcNaNaiwstYG5gknWvbw0Cd6QbttswomzMZ7G6drlSxsSCxMuW4hHRVew60P78iuWGi+cigAzIuck38Xur+KHrAC8FGX1VE3c2MkpEFOaRGAYAo5msd5wKit683GsqTE5WO2yU1wgG4HqOfg7dTZeqG+BnGJCwO7A6KrWYjUhcVM9Vrh/u6fG5uyNO/UBSGJXGOPK+A0+SawsRMivnrsaiS/yHpufq9BPsVkG+BePXbEUS5kDzDkgSL13mADtC06rk2yIWHdZ1bgTbj4C9vGxA7yg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: harbor-credentials
      namespace: harbor
