apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
- ../common
helmCharts:
- name: harbor
  includeCRDs: true
  namespace: harbor
  releaseName: harbor
  repo: https://helm.goharbor.io
  version: v1.17.1
  valuesFile: values.yaml
