apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mgmt-harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mgmt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  source:
    repoURL: https://github.com/Dayzpd/kustomize-harbor
    targetRevision: HEAD
    path: overlays/mgmt
  destination:
    name: in-cluster
    namespace: harbor
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
      - /spec/volumeClaimTemplates/0/apiVersion
      - /spec/volumeClaimTemplates/0/kind